const User = require('./User')
const WishList = require('./WishList')
const Contact = require('./ContactUs')
const About = require('./admin/About')
const ContactUs = require('./admin/ContactUs')
const linkSchema = require('./admin/linkSchema')
const PrivayPolicy = require('./admin/PrivacyPolicy')
const ReturnPolicy = require('./admin/ReturndPolicy')
const Setting = require('./admin/Setting')
const ShopByCategory = require('./admin/ShopByCategory')
const TermAndCondition = require('./admin/TermAndCondition')
const Blog = require('./blog/Blog')
const BlogBanner = require('./blog/BlogBanner')
const Coupon = require('./coupon/Coupon')
const CouponUsageUser = require('./coupon/CouponUsageUser')
const Cart = require('./product/Cart')
const Category = require('./product/Category')
const Feedback = require('./product/Feedback')
const Order = require('./product/Order')
const Product = require('./product/Product')
const Checkout = require('./Checkout')
const Like = require('./Like')
const Deit = require('./admin/Deit')
const QueAndAns = require('./admin/QueAndAns')

const initModels = () => {
  User()
  WishList()
  Contact()
  About()
  ContactUs()
  linkSchema()
  PrivayPolicy()
  ReturnPolicy()
  Setting()
  ShopByCategory()
  TermAndCondition()
  Blog()
  BlogBanner()
  Coupon()
  CouponUsageUser()
  Cart()
  Category()
  Feedback()
  Order()
  Product()
  Checkout()
  Like()
  Deit()
  QueAndAns()
}

module.exports = { initModels }
